// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLq6UZsTOiRA8MTaWG9MRAYpWTqDXJFY',
    appId: '1:327869118861:web:47dae1982ada2cfdf4e5c4',
    messagingSenderId: '327869118861',
    projectId: 'flutter-login-f4107',
    authDomain: 'flutter-login-f4107.firebaseapp.com',
    storageBucket: 'flutter-login-f4107.appspot.com',
    measurementId: 'G-MV9WTXCVEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGlRYD0iDJf8xmO859M44BmDD78rgq38',
    appId: '1:327869118861:android:6d2fbcce5ad2e930f4e5c4',
    messagingSenderId: '327869118861',
    projectId: 'flutter-login-f4107',
    storageBucket: 'flutter-login-f4107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmf3lQVVNRpaGNF9wYqecqAnteLSyrUA',
    appId: '1:327869118861:ios:594d5a9f36b4e303f4e5c4',
    messagingSenderId: '327869118861',
    projectId: 'flutter-login-f4107',
    storageBucket: 'flutter-login-f4107.appspot.com',
    androidClientId: '327869118861-2nd83o3gt9j9bkrdvld6a56ks6gmkg9r.apps.googleusercontent.com',
    iosClientId: '327869118861-d6h1nepseoinqil738quls4lg4mlejpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.egyptEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmf3lQVVNRpaGNF9wYqecqAnteLSyrUA',
    appId: '1:327869118861:ios:594d5a9f36b4e303f4e5c4',
    messagingSenderId: '327869118861',
    projectId: 'flutter-login-f4107',
    storageBucket: 'flutter-login-f4107.appspot.com',
    androidClientId: '327869118861-2nd83o3gt9j9bkrdvld6a56ks6gmkg9r.apps.googleusercontent.com',
    iosClientId: '327869118861-d6h1nepseoinqil738quls4lg4mlejpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.egyptEye',
  );
}
